import {
  CallChatLinear,
  CalendarLinear,
  CalendarMinimalisticLinear,
  ClipboardListLinear,
  CheckCircleLinear,
  DocumentTextLinear,
} from 'solar-icon-set';

export const AWV_PATIENTS = [
  { initials:'AB', name:'Anna Brown',       memberId:'#324966', gender:'F', age:'58y 2m', statusCode:'En', utr:'UTR(45d)', status:'New',       admitClass:'Inpatient', nextActionDue:'04/15/2026', nextActionCount:3, lastActionMissed:'03/20/2026', lastMissedCount:2, lastOutreach:{ status:'Successful',    date:'3/12/26', dots:['#CF1322','#CF1322','#059669'] }, assigneeInit:'RW', assignee:'Dr. Deborah Hintz',   startDate:'08/03/2024', lastAdmission:'03/01/2026', laceAcuity:7,  readmission:'No',  riskLevel:'High Risk',   tasks:7, carePlan:'Signed',       action:'View Program'     },
  { initials:'HB', name:'Harold Baker',     memberId:'#312841', gender:'M', age:'67y 5m', statusCode:'NE', utr:'UTR(12d)', status:'Engaged',   admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'-',           lastMissedCount:null, lastOutreach:null, assigneeInit:'EC', assignee:'Dr. Emily Carter',    startDate:'09/15/2024', lastAdmission:'03/15/2026', laceAcuity:5,  readmission:'Yes', riskLevel:'Medium Risk', tasks:5, carePlan:'No Care Plan', action:'Launch Program'   },
  { initials:'CL', name:'Christine Lewis',  memberId:'#298453', gender:'F', age:'72y 1m', statusCode:'En', utr:'UTR(30d)', status:'New',       admitClass:'-',         nextActionDue:'04/18/2026', nextActionCount:5, lastActionMissed:'03/25/2026', lastMissedCount:1, lastOutreach:{ status:'Unsuccessful',     date:'4/01/26', dots:['#CF1322','#CF1322'] }, assigneeInit:'JP', assignee:'Dr. James Park',      startDate:'10/02/2024', lastAdmission:'02/20/2026', laceAcuity:4,  readmission:'No',  riskLevel:'Low Risk',    tasks:4, carePlan:'No Care Plan', action:'Begin Program'    },
  { initials:'DS', name:'David Scott',      memberId:'#341287', gender:'M', age:'64y 8m', statusCode:'Co', utr:'UTR(7d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'04/22/2026', nextActionCount:2, lastActionMissed:'04/10/2026', lastMissedCount:3, lastOutreach:{ status:'Successful',    date:'4/05/26', dots:['#CF1322','#059669','#059669'] }, assigneeInit:'SJ', assignee:'Dr. Sarah Johnson',   startDate:'07/28/2024', lastAdmission:'03/28/2026', laceAcuity:8,  readmission:'Yes', riskLevel:'High Risk',   tasks:6, carePlan:'Signed',       action:'Finalize Program' },
  { initials:'ET', name:'Emily Torres',     memberId:'#309128', gender:'F', age:'55y 4m', statusCode:'NE', utr:'UTR(60d)', status:'New',       admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'-',           lastMissedCount:null, lastOutreach:null, assigneeInit:'AW', assignee:'Dr. Alex Wong',       startDate:'11/10/2024', lastAdmission:'03/20/2026', laceAcuity:3,  readmission:'No',  riskLevel:'Low Risk',    tasks:2, carePlan:'Pending',      action:'Kickoff Program'  },
  { initials:'FB', name:'Frank Bishop',     memberId:'#287654', gender:'M', age:'79y 0m', statusCode:'En', utr:'UTR(21d)', status:'Engaged',   admitClass:'-',         nextActionDue:'04/12/2026', nextActionCount:4, lastActionMissed:'03/30/2026', lastMissedCount:1, lastOutreach:{ status:'Note', date:'3/28/26', dots:['#CF1322'] }, assigneeInit:'MG', assignee:'Dr. Maria Gomez',     startDate:'08/20/2024', lastAdmission:'02/28/2026', laceAcuity:6,  readmission:'No',  riskLevel:'Medium Risk', tasks:3, carePlan:'Signed',       action:'Assess Program'   },
  { initials:'GD', name:'Grace Davis',      memberId:'#318975', gender:'F', age:'61y 9m', statusCode:'NE', utr:'UTR(90d)', status:'New',       admitClass:'-',         nextActionDue:'04/28/2026', nextActionCount:6, lastActionMissed:'04/18/2026', lastMissedCount:3, lastOutreach:{ status:'Note',     date:'4/10/26', dots:['#CF1322','#CF1322'] }, assigneeInit:'KP', assignee:'Dr. Kevin Patel',     startDate:'12/05/2024', lastAdmission:'04/01/2026', laceAcuity:5,  readmission:'Yes', riskLevel:'High Risk',   tasks:5, carePlan:'No Care Plan', action:'Review Program'   },
  { initials:'HW', name:'Henry Wilson',     memberId:'#302341', gender:'M', age:'70y 6m', statusCode:'Co', utr:'UTR(3d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'04/30/2026', nextActionCount:2, lastActionMissed:'-',           lastMissedCount:null, lastOutreach:{ status:'Successful',    date:'4/15/26', dots:['#CF1322','#059669'] }, assigneeInit:'LC', assignee:'Dr. Linda Chen',      startDate:'06/15/2024', lastAdmission:'04/10/2026', laceAcuity:9,  readmission:'Yes', riskLevel:'High Risk',   tasks:4, carePlan:'Signed',       action:'Expand Program'   },
  { initials:'IM', name:'Irene Martinez',   memberId:'#295867', gender:'F', age:'68y 3m', statusCode:'En', utr:'UTR(15d)', status:'Engaged',   admitClass:'-',         nextActionDue:'05/02/2026', nextActionCount:3, lastActionMissed:'04/25/2026', lastMissedCount:2, lastOutreach:{ status:'Unsuccessful',     date:'4/20/26', dots:['#CF1322','#CF1322','#CF1322'] }, assigneeInit:'RL', assignee:'Dr. Robert Lee',      startDate:'09/30/2024', lastAdmission:'03/05/2026', laceAcuity:4,  readmission:'No',  riskLevel:'Medium Risk', tasks:7, carePlan:'No Care Plan', action:'Launch Program'   },
  { initials:'JT', name:'Julia Thompson',   memberId:'#334512', gender:'F', age:'53y 11m', statusCode:'NE', utr:'UTR(45d)', status:'Engaged',  admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'04/28/2026', lastMissedCount:4, lastOutreach:null,                                                                               assigneeInit:'SH', assignee:'Dr. Samantha Hughes', startDate:'10/20/2024', lastAdmission:'04/18/2026', laceAcuity:6,  readmission:'Yes', riskLevel:'Medium Risk', tasks:2,  carePlan:'Pending',      action:'Complete Program' },

  { initials:'KR', name:'Kevin Ross',        memberId:'#356781', gender:'M', age:'74y 2m',  statusCode:'En', utr:'UTR(18d)', status:'New',       admitClass:'Inpatient', nextActionDue:'05/05/2026', nextActionCount:2,    lastActionMissed:'04/22/2026', lastMissedCount:1,    lastOutreach:{ status:'Successful',    date:'4/28/26', dots:['#059669','#059669'] },             assigneeInit:'RW', assignee:'Dr. Deborah Hintz',   startDate:'01/14/2025', lastAdmission:'04/20/2026', laceAcuity:8,  readmission:'No',  riskLevel:'High Risk',   tasks:6,  carePlan:'Signed',       action:'View Program'     },
  { initials:'LN', name:'Laura Nelson',      memberId:'#321098', gender:'F', age:'60y 7m',  statusCode:'Co', utr:'UTR(5d)',  status:'Completed', admitClass:'-',         nextActionDue:'05/08/2026', nextActionCount:3,    lastActionMissed:'-',           lastMissedCount:null, lastOutreach:{ status:'Note', date:'5/01/26', dots:['#CF1322'] },                           assigneeInit:'EC', assignee:'Dr. Emily Carter',    startDate:'02/03/2025', lastAdmission:'03/25/2026', laceAcuity:4,  readmission:'No',  riskLevel:'Low Risk',    tasks:3,  carePlan:'No Care Plan', action:'Finalize Program' },
  { initials:'MF', name:'Michael Foster',    memberId:'#309874', gender:'M', age:'81y 0m',  statusCode:'En', utr:'UTR(33d)', status:'Engaged',   admitClass:'-',         nextActionDue:'05/10/2026', nextActionCount:5,    lastActionMissed:'04/30/2026', lastMissedCount:2,    lastOutreach:null,                                                                               assigneeInit:'JP', assignee:'Dr. James Park',      startDate:'11/28/2024', lastAdmission:'04/05/2026', laceAcuity:7,  readmission:'Yes', riskLevel:'High Risk',   tasks:4,  carePlan:'Pending',      action:'Assess Program'   },
  { initials:'NP', name:'Nancy Parker',      memberId:'#342567', gender:'F', age:'66y 4m',  statusCode:'NE', utr:'UTR(22d)', status:'New',       admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'-',           lastMissedCount:null, lastOutreach:null,                                                                               assigneeInit:'SJ', assignee:'Dr. Sarah Johnson',   startDate:'12/10/2024', lastAdmission:'03/30/2026', laceAcuity:3,  readmission:'No',  riskLevel:'Low Risk',    tasks:1,  carePlan:'No Care Plan', action:'Kickoff Program'  },
  { initials:'OC', name:'Oscar Chen',        memberId:'#287345', gender:'M', age:'69y 9m',  statusCode:'Co', utr:'UTR(9d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'05/12/2026', nextActionCount:1,    lastActionMissed:'04/20/2026', lastMissedCount:3,    lastOutreach:{ status:'Successful',    date:'5/05/26', dots:['#CF1322','#CF1322','#059669'] },      assigneeInit:'AW', assignee:'Dr. Alex Wong',       startDate:'08/22/2024', lastAdmission:'05/01/2026', laceAcuity:6,  readmission:'Yes', riskLevel:'Medium Risk', tasks:5,  carePlan:'Signed',       action:'Expand Program'   },
  { initials:'PR', name:'Patricia Reed',     memberId:'#318234', gender:'F', age:'57y 6m',  statusCode:'En', utr:'UTR(41d)', status:'New',       admitClass:'-',         nextActionDue:'05/14/2026', nextActionCount:4,    lastActionMissed:'05/02/2026', lastMissedCount:2,    lastOutreach:{ status:'Unsuccessful',     date:'5/07/26', dots:['#CF1322','#CF1322'] },              assigneeInit:'MG', assignee:'Dr. Maria Gomez',     startDate:'01/07/2025', lastAdmission:'04/28/2026', laceAcuity:5,  readmission:'No',  riskLevel:'Medium Risk', tasks:8,  carePlan:'No Care Plan', action:'Begin Program'    },
  { initials:'QM', name:'Quinton Miles',     memberId:'#301456', gender:'M', age:'75y 1m',  statusCode:'NE', utr:'UTR(55d)', status:'Engaged',   admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'05/05/2026', lastMissedCount:1,    lastOutreach:null,                                                                               assigneeInit:'KP', assignee:'Dr. Kevin Patel',     startDate:'09/12/2024', lastAdmission:'04/15/2026', laceAcuity:9,  readmission:'Yes', riskLevel:'High Risk',   tasks:3,  carePlan:'Pending',      action:'Launch Program'   },
  { initials:'RS', name:'Rachel Stone',      memberId:'#336789', gender:'F', age:'62y 3m',  statusCode:'En', utr:'UTR(14d)', status:'New',       admitClass:'Inpatient', nextActionDue:'05/16/2026', nextActionCount:6,    lastActionMissed:'04/25/2026', lastMissedCount:4,    lastOutreach:{ status:'Note',     date:'5/10/26', dots:['#CF1322'] },                          assigneeInit:'LC', assignee:'Dr. Linda Chen',      startDate:'03/18/2025', lastAdmission:'05/05/2026', laceAcuity:7,  readmission:'No',  riskLevel:'High Risk',   tasks:6,  carePlan:'Signed',       action:'Review Program'   },
  { initials:'ST', name:'Samuel Turner',     memberId:'#293012', gender:'M', age:'78y 8m',  statusCode:'Co', utr:'UTR(2d)',  status:'Completed', admitClass:'-',         nextActionDue:'05/18/2026', nextActionCount:2,    lastActionMissed:'-',           lastMissedCount:null, lastOutreach:{ status:'Successful',    date:'5/12/26', dots:['#059669','#059669'] },             assigneeInit:'RL', assignee:'Dr. Robert Lee',      startDate:'07/05/2024', lastAdmission:'05/08/2026', laceAcuity:4,  readmission:'No',  riskLevel:'Low Risk',    tasks:2,  carePlan:'No Care Plan', action:'Complete Program'  },
  { initials:'TW', name:'Teresa Walsh',      memberId:'#348901', gender:'F', age:'55y 10m', statusCode:'NE', utr:'UTR(67d)', status:'Engaged',   admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'05/08/2026', lastMissedCount:3,    lastOutreach:null,                                                                               assigneeInit:'SH', assignee:'Dr. Samantha Hughes', startDate:'02/25/2025', lastAdmission:'04/22/2026', laceAcuity:5,  readmission:'Yes', riskLevel:'Medium Risk', tasks:4,  carePlan:'Pending',      action:'Assess Program'   },
  { initials:'UH', name:'Ulric Hammond',     memberId:'#312678', gender:'M', age:'72y 5m',  statusCode:'En', utr:'UTR(28d)', status:'New',       admitClass:'Inpatient', nextActionDue:'05/20/2026', nextActionCount:3,    lastActionMissed:'05/10/2026', lastMissedCount:1,    lastOutreach:{ status:'Note', date:'5/15/26', dots:['#CF1322','#CF1322'] },              assigneeInit:'RW', assignee:'Dr. Deborah Hintz',   startDate:'01/30/2025', lastAdmission:'05/12/2026', laceAcuity:8,  readmission:'Yes', riskLevel:'High Risk',   tasks:7,  carePlan:'Signed',       action:'View Program'     },
  { initials:'VJ', name:'Vivian James',      memberId:'#325890', gender:'F', age:'63y 0m',  statusCode:'Co', utr:'UTR(11d)', status:'Completed', admitClass:'-',         nextActionDue:'05/22/2026', nextActionCount:4,    lastActionMissed:'-',           lastMissedCount:null, lastOutreach:{ status:'Successful',    date:'5/18/26', dots:['#CF1322','#059669','#059669'] },      assigneeInit:'EC', assignee:'Dr. Emily Carter',    startDate:'08/14/2024', lastAdmission:'05/15/2026', laceAcuity:3,  readmission:'No',  riskLevel:'Low Risk',    tasks:5,  carePlan:'Signed',       action:'Finalize Program' },
  { initials:'WB', name:'Walter Barnes',     memberId:'#297234', gender:'M', age:'80y 3m',  statusCode:'NE', utr:'UTR(38d)', status:'Engaged',   admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'05/12/2026', lastMissedCount:2,    lastOutreach:null,                                                                               assigneeInit:'JP', assignee:'Dr. James Park',      startDate:'10/08/2024', lastAdmission:'04/30/2026', laceAcuity:6,  readmission:'Yes', riskLevel:'Medium Risk', tasks:3,  carePlan:'No Care Plan', action:'Launch Program'   },
  { initials:'XC', name:'Xena Collins',      memberId:'#340123', gender:'F', age:'58y 7m',  statusCode:'En', utr:'UTR(19d)', status:'New',       admitClass:'-',         nextActionDue:'05/24/2026', nextActionCount:5,    lastActionMissed:'05/14/2026', lastMissedCount:3,    lastOutreach:{ status:'Unsuccessful',     date:'5/20/26', dots:['#CF1322','#CF1322','#CF1322'] },      assigneeInit:'SJ', assignee:'Dr. Sarah Johnson',   startDate:'03/03/2025', lastAdmission:'05/18/2026', laceAcuity:5,  readmission:'No',  riskLevel:'Medium Risk', tasks:9,  carePlan:'No Care Plan', action:'Begin Program'    },
  { initials:'YM', name:'Yvonne Morgan',     memberId:'#308567', gender:'F', age:'67y 2m',  statusCode:'Co', utr:'UTR(6d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'05/26/2026', nextActionCount:1,    lastActionMissed:'05/16/2026', lastMissedCount:1,    lastOutreach:{ status:'Successful',    date:'5/22/26', dots:['#059669'] },                          assigneeInit:'AW', assignee:'Dr. Alex Wong',       startDate:'06/20/2024', lastAdmission:'05/20/2026', laceAcuity:9,  readmission:'Yes', riskLevel:'High Risk',   tasks:4,  carePlan:'Signed',       action:'Expand Program'   },
  { initials:'ZP', name:'Zachary Powell',    memberId:'#322345', gender:'M', age:'71y 11m', statusCode:'NE', utr:'UTR(48d)', status:'New',       admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'-',           lastMissedCount:null, lastOutreach:null,                                                                               assigneeInit:'MG', assignee:'Dr. Maria Gomez',     startDate:'11/15/2024', lastAdmission:'05/10/2026', laceAcuity:2,  readmission:'No',  riskLevel:'Low Risk',    tasks:1,  carePlan:'Pending',      action:'Kickoff Program'  },
  { initials:'AF', name:'Alice Fleming',     memberId:'#337890', gender:'F', age:'64y 4m',  statusCode:'En', utr:'UTR(26d)', status:'Engaged',   admitClass:'-',         nextActionDue:'05/28/2026', nextActionCount:6,    lastActionMissed:'05/18/2026', lastMissedCount:4,    lastOutreach:{ status:'Note',     date:'5/24/26', dots:['#CF1322','#CF1322'] },              assigneeInit:'KP', assignee:'Dr. Kevin Patel',     startDate:'02/12/2025', lastAdmission:'05/22/2026', laceAcuity:6,  readmission:'Yes', riskLevel:'High Risk',   tasks:8,  carePlan:'No Care Plan', action:'Review Program'   },
  { initials:'BK', name:'Benjamin Kirk',     memberId:'#295678', gender:'M', age:'76y 6m',  statusCode:'Co', utr:'UTR(4d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'05/30/2026', nextActionCount:2,    lastActionMissed:'-',           lastMissedCount:null, lastOutreach:{ status:'Successful',    date:'5/26/26', dots:['#CF1322','#059669'] },              assigneeInit:'LC', assignee:'Dr. Linda Chen',      startDate:'07/28/2024', lastAdmission:'05/25/2026', laceAcuity:7,  readmission:'No',  riskLevel:'Medium Risk', tasks:5,  carePlan:'Signed',       action:'Complete Program'  },
  { initials:'CA', name:'Clara Avery',       memberId:'#311234', gender:'F', age:'59y 9m',  statusCode:'NE', utr:'UTR(72d)', status:'New',       admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'05/20/2026', lastMissedCount:2,    lastOutreach:null,                                                                               assigneeInit:'RL', assignee:'Dr. Robert Lee',      startDate:'12/22/2024', lastAdmission:'05/15/2026', laceAcuity:4,  readmission:'Yes', riskLevel:'Medium Risk', tasks:3,  carePlan:'Pending',      action:'Assess Program'   },
  { initials:'DH', name:'Douglas Hale',      memberId:'#344567', gender:'M', age:'83y 1m',  statusCode:'En', utr:'UTR(16d)', status:'Engaged',   admitClass:'-',         nextActionDue:'06/01/2026', nextActionCount:3,    lastActionMissed:'05/22/2026', lastMissedCount:1,    lastOutreach:{ status:'Note', date:'5/28/26', dots:['#CF1322'] },                          assigneeInit:'SH', assignee:'Dr. Samantha Hughes', startDate:'09/05/2024', lastAdmission:'05/28/2026', laceAcuity:8,  readmission:'No',  riskLevel:'High Risk',   tasks:6,  carePlan:'No Care Plan', action:'Launch Program'   },
  { initials:'EV', name:'Eleanor Vance',     memberId:'#300789', gender:'F', age:'61y 5m',  statusCode:'Co', utr:'UTR(8d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'06/03/2026', nextActionCount:4,    lastActionMissed:'05/24/2026', lastMissedCount:3,    lastOutreach:{ status:'Unsuccessful',     date:'5/30/26', dots:['#CF1322','#CF1322'] },              assigneeInit:'RW', assignee:'Dr. Deborah Hintz',   startDate:'04/10/2025', lastAdmission:'05/30/2026', laceAcuity:5,  readmission:'Yes', riskLevel:'Medium Risk', tasks:7,  carePlan:'Signed',       action:'Finalize Program' },
  { initials:'FO', name:'Felix Ortega',      memberId:'#326012', gender:'M', age:'68y 0m',  statusCode:'NE', utr:'UTR(53d)', status:'New',       admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'-',           lastMissedCount:null, lastOutreach:null,                                                                               assigneeInit:'EC', assignee:'Dr. Emily Carter',    startDate:'01/18/2025', lastAdmission:'05/20/2026', laceAcuity:3,  readmission:'No',  riskLevel:'Low Risk',    tasks:2,  carePlan:'No Care Plan', action:'Kickoff Program'  },
  { initials:'GN', name:'Gloria Nash',       memberId:'#339234', gender:'F', age:'73y 8m',  statusCode:'En', utr:'UTR(31d)', status:'Engaged',   admitClass:'-',         nextActionDue:'06/05/2026', nextActionCount:5,    lastActionMissed:'05/26/2026', lastMissedCount:2,    lastOutreach:{ status:'Successful',    date:'6/01/26', dots:['#CF1322','#CF1322','#059669'] },      assigneeInit:'JP', assignee:'Dr. James Park',      startDate:'08/30/2024', lastAdmission:'06/01/2026', laceAcuity:6,  readmission:'Yes', riskLevel:'High Risk',   tasks:4,  carePlan:'Pending',      action:'Begin Program'    },
  { initials:'HY', name:'Howard Young',      memberId:'#297456', gender:'M', age:'77y 3m',  statusCode:'Co', utr:'UTR(1d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'06/07/2026', nextActionCount:1,    lastActionMissed:'-',           lastMissedCount:null, lastOutreach:{ status:'Successful',    date:'6/03/26', dots:['#059669','#059669','#059669'] },      assigneeInit:'SJ', assignee:'Dr. Sarah Johnson',   startDate:'05/16/2024', lastAdmission:'06/03/2026', laceAcuity:9,  readmission:'No',  riskLevel:'High Risk',   tasks:3,  carePlan:'Signed',       action:'Expand Program'   },
  { initials:'IA', name:'Isabelle Archer',   memberId:'#313678', gender:'F', age:'54y 6m',  statusCode:'NE', utr:'UTR(44d)', status:'New',       admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'05/28/2026', lastMissedCount:5,    lastOutreach:null,                                                                               assigneeInit:'AW', assignee:'Dr. Alex Wong',       startDate:'03/28/2025', lastAdmission:'05/25/2026', laceAcuity:4,  readmission:'Yes', riskLevel:'Medium Risk', tasks:10, carePlan:'No Care Plan', action:'Review Program'   },
  { initials:'JD', name:'Jerome Dixon',      memberId:'#328901', gender:'M', age:'70y 1m',  statusCode:'En', utr:'UTR(23d)', status:'Engaged',   admitClass:'-',         nextActionDue:'06/09/2026', nextActionCount:3,    lastActionMissed:'05/30/2026', lastMissedCount:1,    lastOutreach:{ status:'Note',     date:'6/05/26', dots:['#CF1322','#CF1322'] },              assigneeInit:'MG', assignee:'Dr. Maria Gomez',     startDate:'10/14/2024', lastAdmission:'06/05/2026', laceAcuity:5,  readmission:'No',  riskLevel:'Medium Risk', tasks:6,  carePlan:'No Care Plan', action:'Launch Program'   },
  { initials:'KL', name:'Katherine Lane',    memberId:'#342123', gender:'F', age:'65y 10m', statusCode:'Co', utr:'UTR(7d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'06/11/2026', nextActionCount:2,    lastActionMissed:'06/01/2026', lastMissedCount:2,    lastOutreach:{ status:'Successful',    date:'6/07/26', dots:['#CF1322','#059669'] },              assigneeInit:'KP', assignee:'Dr. Kevin Patel',     startDate:'06/02/2024', lastAdmission:'06/07/2026', laceAcuity:7,  readmission:'Yes', riskLevel:'High Risk',   tasks:5,  carePlan:'Signed',       action:'Complete Program'  },
  { initials:'LG', name:'Leonard Grant',     memberId:'#300345', gender:'M', age:'82y 7m',  statusCode:'NE', utr:'UTR(61d)', status:'New',       admitClass:'-',         nextActionDue:'-',           nextActionCount:null, lastActionMissed:'-',           lastMissedCount:null, lastOutreach:null,                                                                               assigneeInit:'LC', assignee:'Dr. Linda Chen',      startDate:'11/01/2024', lastAdmission:'05/30/2026', laceAcuity:8,  readmission:'No',  riskLevel:'High Risk',   tasks:2,  carePlan:'Pending',      action:'View Program'     },
  { initials:'MB', name:'Miriam Bell',       memberId:'#315567', gender:'F', age:'56y 2m',  statusCode:'En', utr:'UTR(35d)', status:'Engaged',   admitClass:'-',         nextActionDue:'06/13/2026', nextActionCount:7,    lastActionMissed:'06/03/2026', lastMissedCount:3,    lastOutreach:{ status:'Note', date:'6/09/26', dots:['#CF1322','#CF1322'] },              assigneeInit:'RL', assignee:'Dr. Robert Lee',      startDate:'02/20/2025', lastAdmission:'06/09/2026', laceAcuity:4,  readmission:'Yes', riskLevel:'Medium Risk', tasks:8,  carePlan:'No Care Plan', action:'Assess Program'   },
  { initials:'NC', name:'Nathan Cruz',       memberId:'#329789', gender:'M', age:'79y 4m',  statusCode:'Co', utr:'UTR(3d)',  status:'Completed', admitClass:'Inpatient', nextActionDue:'06/15/2026', nextActionCount:4,    lastActionMissed:'06/05/2026', lastMissedCount:2,    lastOutreach:{ status:'Unsuccessful',     date:'6/11/26', dots:['#CF1322','#CF1322','#CF1322'] },      assigneeInit:'SH', assignee:'Dr. Samantha Hughes', startDate:'09/25/2024', lastAdmission:'06/11/2026', laceAcuity:6,  readmission:'No',  riskLevel:'Medium Risk', tasks:3,  carePlan:'Signed',       action:'Finalize Program' },
];

export const PATIENT_TOOLTIP_ITEMS = {
  'Anna Brown':      { dueItems:[{label:'Initial Outreach',attempts:'3 Attempts'},{label:'MRP Completion'},{label:'Task For Med Recon'}],         missedItems:[{label:'Post Discharge Appointment'},{label:'MRP Completion'}] },
  'Christine Lewis': { dueItems:[{label:'Follow Up Outreach 2'},{label:'Post IP Assessment'},{label:'Assessments'}],                                       missedItems:[{label:'Initial Outreach',attempts:'2 Attempts'}] },
  'David Scott':     { dueItems:[{label:'Follow Up Outreach 1'},{label:'MRP Completion'}],                                                                  missedItems:[{label:'Follow Up Outreach 1'},{label:'Task For Med Recon'},{label:'Post IP Assessment'}] },
  'Frank Bishop':    { dueItems:[{label:'Initial Outreach',attempts:'2 Attempts'},{label:'Task For Med Recon'},{label:'Program Completion'}],       missedItems:[{label:'MRP Completion'}] },
  'Grace Davis':     { dueItems:[{label:'Follow Up Outreach 3'},{label:'Post Discharge Appointment'},{label:'Assessments'}],                                missedItems:[{label:'Follow Up Outreach 3'},{label:'Post Discharge Appointment'},{label:'Assessments'}] },
  'Henry Wilson':    { dueItems:[{label:'Follow Up Outreach 1'},{label:'Tasks'}] },
  'Irene Martinez':  { dueItems:[{label:'Follow Up Outreach 2'},{label:'MRP Completion'},{label:'Appointments'}],                                           missedItems:[{label:'Initial Outreach',attempts:'3 Attempts'},{label:'Follow Up Outreach 1'}] },
  'Julia Thompson':  { missedItems:[{label:'Follow Up Outreach 2'},{label:'Task For Med Recon'},{label:'Program Completion'},{label:'Assessments'}] },
  'Kevin Ross':      { dueItems:[{label:'Initial Outreach',attempts:'2 Attempts'},{label:'Task For Med Recon'}],                                   missedItems:[{label:'Post Discharge Appointment'}] },
  'Laura Nelson':    { dueItems:[{label:'Follow Up Outreach 4'},{label:'Post IP Assessment'},{label:'Program Completion'}] },
  'Michael Foster':  { dueItems:[{label:'Follow Up Outreach 1'},{label:'Assessments'},{label:'Tasks'}],                                                     missedItems:[{label:'Follow Up Outreach 4'},{label:'MRP Completion'}] },
  'Oscar Chen':      { dueItems:[{label:'MRP Completion'}],                                                                                        missedItems:[{label:'Follow Up Outreach 1'},{label:'Task For Med Recon'},{label:'Post IP Assessment'}] },
  'Patricia Reed':   { dueItems:[{label:'Follow Up Outreach 2'},{label:'Post Discharge Appointment'},{label:'Assessments'}],                                missedItems:[{label:'Initial Outreach',attempts:'2 Attempts'},{label:'Appointments'}] },
  'Quinton Miles':   { missedItems:[{label:'Tasks'}] },
  'Rachel Stone':    { dueItems:[{label:'Follow Up Outreach 5'},{label:'Program Completion'},{label:'Tasks'},{label:'Appointments'}],                       missedItems:[{label:'Follow Up Outreach 5'},{label:'Post IP Assessment'},{label:'Program Completion'},{label:'Appointments'}] },
  'Samuel Turner':   { dueItems:[{label:'Initial Outreach',attempts:'3 Attempts'},{label:'MRP Completion'}] },
  'Teresa Walsh':    { missedItems:[{label:'Follow Up Outreach 2'},{label:'MRP Completion'},{label:'Assessments'}] },
  'Ulric Hammond':   { dueItems:[{label:'Follow Up Outreach 3'},{label:'Task For Med Recon'},{label:'Post IP Assessment'}],                                 missedItems:[{label:'Task For Med Recon'}] },
  'Vivian James':    { dueItems:[{label:'Follow Up Outreach 1'},{label:'Assessments'},{label:'Appointments'}] },
  'Walter Barnes':   { missedItems:[{label:'Follow Up Outreach 3'},{label:'Post Discharge Appointment'}] },
  'Xena Collins':    { dueItems:[{label:'Follow Up Outreach 4'},{label:'MRP Completion'},{label:'Program Completion'}],                                     missedItems:[{label:'Initial Outreach',attempts:'2 Attempts'},{label:'Follow Up Outreach 1'},{label:'Tasks'}] },
  'Yvonne Morgan':   { dueItems:[{label:'Tasks'}],                                                                                                 missedItems:[{label:'Post IP Assessment'}] },
  'Alice Fleming':   { dueItems:[{label:'Follow Up Outreach 2'},{label:'Post Discharge Appointment'},{label:'Task For Med Recon'},{label:'Assessments'}],   missedItems:[{label:'Follow Up Outreach 2'},{label:'Task For Med Recon'},{label:'Assessments'},{label:'Program Completion'}] },
  'Benjamin Kirk':   { dueItems:[{label:'Initial Outreach',attempts:'3 Attempts'},{label:'Follow Up Outreach 1'}] },
  'Clara Avery':     { missedItems:[{label:'Follow Up Outreach 4'},{label:'MRP Completion'}] },
  'Douglas Hale':    { dueItems:[{label:'Follow Up Outreach 5'},{label:'MRP Completion'},{label:'Tasks'}],                                                  missedItems:[{label:'Tasks'}] },
  'Eleanor Vance':   { dueItems:[{label:'Follow Up Outreach 3'},{label:'Post IP Assessment'},{label:'Appointments'}],                                       missedItems:[{label:'Follow Up Outreach 1'},{label:'Post Discharge Appointment'},{label:'Assessments'}] },
  'Gloria Nash':     { dueItems:[{label:'Follow Up Outreach 2'},{label:'Assessments'},{label:'Program Completion'}],                                        missedItems:[{label:'Follow Up Outreach 5'},{label:'MRP Completion'}] },
  'Howard Young':    { dueItems:[{label:'Post Discharge Appointment'}] },
  'Isabelle Archer': { missedItems:[{label:'Initial Outreach',attempts:'2 Attempts'},{label:'Follow Up Outreach 2'},{label:'Task For Med Recon'}] },
  'Jerome Dixon':    { dueItems:[{label:'Follow Up Outreach 1'},{label:'Task For Med Recon'},{label:'MRP Completion'}],                                     missedItems:[{label:'Post IP Assessment'}] },
  'Katherine Lane':  { dueItems:[{label:'Follow Up Outreach 4'},{label:'Post IP Assessment'}],                                                             missedItems:[{label:'Follow Up Outreach 3'},{label:'Appointments'}] },
  'Miriam Bell':     { dueItems:[{label:'Initial Outreach',attempts:'3 Attempts'},{label:'Follow Up Outreach 3'},{label:'Assessments'}],                    missedItems:[{label:'Follow Up Outreach 4'},{label:'MRP Completion'},{label:'Tasks'}] },
  'Nathan Cruz':     { dueItems:[{label:'Follow Up Outreach 5'},{label:'MRP Completion'},{label:'Tasks'}],                                                  missedItems:[{label:'Follow Up Outreach 1'},{label:'Post Discharge Appointment'}] },
};

export const OUTREACH1_ATTEMPTS = [
  { num:4, due:'04/01/26', day:'Day 3',         timeNote:null,                   conducted:null,                  outcome:null           },
  { num:3, due:'03/31/26', day:'Day 2',         timeNote:'12:00 Noon – 8:00 PM', conducted:'03/31/26 · 2:14 PM',  outcome:'Unsuccessful' },
  { num:2, due:'03/31/26', day:'Day 2',         timeNote:'Before 12:00 Noon',    conducted:'03/31/26 · 10:22 AM', outcome:'Unsuccessful' },
  { num:1, due:'03/30/26', day:'Day 0 / Day 1', timeNote:null,                   conducted:'03/30/26 · 4:45 PM',  outcome:'Unsuccessful' },
];

export const attemptOutcomeColor = (o) =>
  o === 'Successful'   ? '#059669' :
  o === 'Unsuccessful' ? '#CF1322' :
  'var(--neutral-200)';

export const PAGE_SIZE = 10;

export const ACTION_TYPES = ['Initial Outreach','Follow Up Outreach 1','Follow Up Outreach 2','Follow Up Outreach 3','Follow Up Outreach 4','Follow Up Outreach 5','MRP Completion','Assessments','Tasks','Appointments','Program Completion'];

export const ASSIGNEES = [
  { name:'Deborah Hintz',   init:'DH', role:'Co-ordinator'    },
  { name:'Dianne Russell',  init:'RF', role:'Co-ordinator'    },
  { name:'Marvin McKinney', init:'MM', role:'Co-ordinator'    },
  { name:'Bessie Cooper',   init:'BC', role:'Nurse Practicer' },
  { name:'Richard Willson', init:'RW', role:'Nurse Practiner' },
];

export const MILESTONE_ICON_MAP = {
  'Initial Outreach': CallChatLinear, 'Follow Up Outreach 1': CallChatLinear, 'Follow Up Outreach 2': CallChatLinear,
  'Follow Up Outreach 3': CallChatLinear, 'Follow Up Outreach 4': CallChatLinear, 'Follow Up Outreach 5': CallChatLinear,
  'MRP Completion': ClipboardListLinear, 'Task For Med Recon': ClipboardListLinear, 'Tasks': ClipboardListLinear,
  'Post Discharge Appointment': CalendarLinear, 'Post IP Assessment': DocumentTextLinear,
  'Assessments': DocumentTextLinear, 'Program Completion': CheckCircleLinear, 'Appointments': CalendarMinimalisticLinear,
};

export const DATE_OPTIONS = ['Due Today','Due Tomorrow','Due within 48 Hours','Due within 72 Hours','Custom'];

export const FILTER_DEFS = [
  { key:'memberStatus',      label:'Member Status'       },
  { key:'memberPhone',       label:'Member Phone'        },
  { key:'dob',               label:'DOB'                 },
  { key:'gender',            label:'Gender'              },
  { key:'language',          label:'Language'            },
  { key:'zipcode',           label:'Zipcode'             },
  { key:'city',              label:'City'                },
  { key:'stateOfResidence',  label:'State of Residence'  },
  { key:'utrFlag',           label:'UTR Flag'            },
  { key:'utrAge',            label:'UTR Age'             },
  { key:'assignedTo',        label:'Assigned to'         },
  { key:'programSubStatus',  label:'Program Sub Status'  },
  { key:'carePlanStatus',    label:'Care Plan Status'    },
  { key:'populationType',    label:'Population Type'     },
  { key:'programStartDate',  label:'Program Start Date'  },
  { key:'programDueDate',    label:'Program Due Date'    },
  { key:'nextActionDue',     label:'Next Action Due'     },
  { key:'lastActionMissed',  label:'Last Action Missed'  },
  { key:'lastOutreachDate',  label:'Last Outreach Date'  },
  { key:'preferredCallTime', label:'Preferred Call Time' },
];
